version: '3.8'

services:
  app:
    build: .
    container_name: smart-waste-app
    ports:
      - "8082:8082"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://hopper.proxy.rlwy.net:54156/railway?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: iufOxnNGCyoFkhZTuBpzpBSqBVKgmzEO
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - smart-waste-network

networks:
  smart-waste-network:
    driver: bridge
